definitions:
  models.LoginBody:
    properties:
      email:
        example: JohnDoe@mail.com
        type: string
      password:
        type: string
    type: object
  models.RegistrationBody:
    properties:
      age:
        example: "21"
        type: string
      email:
        example: JohnDoe@mail.com
        type: string
      first_name:
        example: John
        type: string
      last_name:
        example: Doe
        type: string
    type: object
  models.User:
    properties:
      age:
        example: "21"
        type: string
      email:
        example: JohnDoe@mail.com
        type: string
      expired_At:
        type: string
      first_name:
        example: John
        type: string
      id:
        type: integer
      last_name:
        example: Doe
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: This is OWallet API
  title: OWallet API
  version: "1.0"
paths:
  /api/login:
    post:
      consumes:
      - application/json
      parameters:
      - description: Credentials
        in: body
        name: Body
        required: true
        schema:
          $ref: '#/definitions/models.LoginBody'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      tags:
      - Auth
  /api/registration:
    post:
      consumes:
      - application/json
      parameters:
      - description: Credentials
        in: body
        name: Body
        required: true
        schema:
          $ref: '#/definitions/models.RegistrationBody'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      tags:
      - Auth
  /api/user:
    post:
      consumes:
      - application/json
      parameters:
      - description: Create user
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/models.User'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      tags:
      - Users
  /api/user/{id}:
    delete:
      consumes:
      - application/json
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      tags:
      - Users
    get:
      consumes:
      - application/json
      parameters:
      - default: Bearer <Add access token here>
        description: Authorization
        in: header
        name: Authorization
        required: true
        type: string
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      tags:
      - Users
    put:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      tags:
      - Users
  /api/users:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      tags:
      - Users
swagger: "2.0"
